//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C:\winspd3d\redline\redline.rc
//
#define VL_R_OpenVerite                 200
#define VL_R_CloseVerite                201
#define VL_R_MemWrite                   204
#define VL_R_MemWriteRect               206
#define VL_R_MemFill                    208
#define VL_R_MemFillRect                209
#define VL_R_SetDisplayBase             210
#define VL_R_SetStereoDisplayBase       211
#define VL_R_SetPalette                 212
#define VL_R_WaitForDisplaySwitch       213
#define VL_R_Sync                       214
#define VL_R_SetTexturePalette          226
#define VL_R_SwapDisplaySurface         227
#define VL_R_FillBuffer                 229
#define VL_R_LoadBuffer                 230
#define VL_R_InstallDstBuffer           235
#define VL_R_InstallTextureMap          236
#define VL_R_InstallTextureMapBasic     237
#define VL_R_InstallZBuffer             238
#define VL_R_CopyBuffer                 240
#define VL_R_BitfillNoPat               241
#define VL_R_BitfillPatTransparent      242
#define VL_R_BitfillPatOpaque           243
#define VL_R_ContextInit                244
#define VL_R_SetSrcBase                 245
#define VL_R_SetSrcFmt                  246
#define VL_R_SetSrcFunc                 247
#define VL_R_SetSrcFilter               248
#define VL_R_SetSrcColorNoPad           249
#define VL_R_SetSwapUV                  250
#define VL_R_SetChromaKey               251
#define VL_R_SetZScissorEnable          252
#define VL_R_SetSrcBGR                  253
#define VL_R_SetUClamp                  254
#define VL_R_SetVClamp                  255
#define VL_R_SetUMask                   256
#define VL_R_SetVMask                   257
#define VL_R_SetUMultiplier             258
#define VL_R_SetVMultiplier             259
#define VL_R_SetSOffset                 260
#define VL_R_SetTOffset                 261
#define VL_R_SetSrcStride               262
#define VL_R_SetDstStride               263
#define VL_R_SetZStride                 264
#define VL_R_SetDstBase                 265
#define VL_R_SetALUMode                 266
#define VL_R_SetBlendSrcFunc            267
#define VL_R_SetBlendDstFunc            268
#define VL_R_SetZBufMode                269
#define VL_R_SetZBufWrMode              270
#define VL_R_SetYUV2RGB                 271
#define VL_R_SetBlendEnable             272
#define VL_R_SetDitherEnable            273
#define VL_R_SetFogEnable               274
#define VL_R_SetDstRdDisable            275
#define VL_R_SetDstBGR                  276
#define VL_R_SetTranspReject            277
#define VL_R_SetAlphaThreshold          278
#define VL_R_SetDstFmt                  279
#define VL_R_SetPMask                   280
#define VL_R_SetPat                     281
#define VL_R_SetPatLength               282
#define VL_R_SetPatEnable               283
#define VL_R_SetPatOpaque               284
#define VL_R_SetPatOffset               285
#define VL_R_SetScissorX                286
#define VL_R_SetScissorY                287
#define VL_R_SetZBase                   288
#define VL_R_SetDitherOffset            289
#define VL_R_SetFGColorABGR             290
#define VL_R_SetFGColorARGB             291
#define VL_R_SetBGColorABGR             292
#define VL_R_SetBGColorARGB             293
#define VL_R_SetFogColorBGR             294
#define VL_R_SetFogColorRGB             295
#define VL_R_SetDstColorABGR            296
#define VL_R_SetDstColorARGB            297
#define VL_R_SetChromaColor             298
#define VL_R_SetChromaMask              299
#define VL_R_SetCurrentTexture          300
#define VL_R_SetZ                       301
#define VL_R_SetR                       302
#define VL_R_SetG                       303
#define VL_R_SetB                       304
#define VL_R_SetA                       305
#define VL_R_SetF                       306
#define VL_R_SetU                       307
#define VL_R_SetV                       308
#define VL_R_VertexSize                 309
#define VL_R_QOffset                    310
#define VL_R_QNormalize                 311
#define VL_R_Dot                        312
#define VL_R_Line                       313
#define VL_R_Polyline                   314
#define VL_R_IntLine                    315
#define VL_R_IntPolyline                316
#define VL_R_AALine                     317
#define VL_R_AAEdge                     318
#define VL_R_Span                       319
#define VL_R_Square                     320
#define VL_R_Rectangle                  321
#define VL_R_Triangle                   322
#define VL_R_TriangleNormQ              323
#define VL_R_Tristrip                   324
#define VL_R_Trifan                     325
#define VL_R_TriangleFill               326
#define VL_R_Affine                     327
#define VL_R_Warp                       328
#define VL_R_Bitblt                     330
#define VL_R_CompositeRect              331
#define VL_R_Bitfill                    333
#define VL_R_BitbltMem                  334
#define VL_R_Lookup                     336
#define VL_R_MemWriteSprite             338
#define VL_R_Particles                  340
#define VL_R_QSpan                      342
#define VL_R_FrameMarker                344
#define VL_R_RegisterErrorHandler       345
#define VL_R_GetFunctionName            346
#define VL_R_GetErrorText               347
#define VL_R_GetLastError               348
#define VL_R_GetExtensions              349
#define VL_R_GetErrorHandler            350
#define VL_R_CreateSurface              351
#define VL_R_DestroySurface             352
#define VL_R_SetSurfaceChromaKey        353
#define VL_R_SetSurfaceChromaColor      354
#define VL_R_SetSurfaceChromaMask       355
#define VL_R_SetSurfaceColorPad         356
#define VL_R_SetSurfaceBGR              357
#define VL_R_SetSurfaceClamp            358
#define VL_R_SetSurfaceTexturePalette   359
#define VL_R_PointSurface               360
#define VL_R_RestoreSurface             361
#define VL_R_SetSpecularEnable          362
#define VL_R_SetSpecularColorRGB        363
#define VL_R_SetSpecularColorBGR        364
#define VL_SUCCESS                      600
#define VL_PARAM_ERROR                  601
#define VL_ALLOC_FAILED                 602
#define VL_BAD_PIXFMT                   603
#define VL_ADDTOCMDLIST_FAILED          624
#define VL_FULLSCREEN_MODE_ONLY         625
#define VL_REQUIRES_BACK_BUFFER         627
#define VL_NO_ERROR                     629
#define VL_OPEN_FAILED                  630
#define VL_CREATE_VERITE                630
#define VL_CANNOT_GET_BOARDINFO         631
#define VL_CANNOT_GET_HANDLE            632
#define VL_OUT_OF_VIDEO_MEMORY          633
#define VL_FAILED                       634

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
