//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C:\winspd3d\verite\verite.rc
//
#define V_R_CreateCmdBuffer             100
#define V_R_IssueCmdBuffer              101
#define V_R_IssueCmdBufferAsync         102
#define V_R_QueryCmdBuffer              103
#define V_R_DestroyCmdBuffer            104
#define V_R_ResetCmdBuffer              105
#define V_R_SetCmdBufferCallBack        106
#define V_R_GetCmdBufferCallBack        107
#define V_R_AddToCmdList                108
#define V_R_AddToDMAList                109
#define V_R_EnumVeriteBoards            110
#define V_R_CreateVerite                111
#define V_R_DestroyVerite               115
#define V_R_CurrentRequest              116
#define V_R_AllocMemoryObject           117
#define V_R_FreeMemoryObject            118
#define V_R_AllocLockedMem              119
#define V_R_FreeLockedMem               120
#define V_R_LockPages                   121
#define V_R_UnlockPages                 122
#define V_R_Linebytes                   123
#define V_R_Stride                      124
#define V_R_GetUserPrivate              125
#define V_R_SetUserPrivate              126
#define V_R_RegisterErrorHandler        127
#define V_R_GetFunctionName             128
#define V_R_GetErrorText                129
#define V_R_GetLastError                130
#define V_R_GetErrorHandler             133
#define V_R_CreateBufferGroup           134
#define V_R_IsBufferLost                135
#define V_R_RestoreBufferGroup          136
#define V_R_PointBufferGroup            137
#define V_R_BltDisplayBuffer            145
#define V_R_LockBuffer                  146
#define V_R_UnlockBuffer                147
#define V_R_DestroyBufferGroup          149
#define V_R_SetDisplayMode              150
#define V_R_SetDisplayType              151
#define V_R_GetDisplayType              152
#define V_R_GetCmdBufferHandle          153
#define V_R_GetUseDMA                   154
#define V_R_GetBufferLinebytes          155
#define V_R_GetBufferStride             156
#define V_R_GetBufferAddress            157
#define V_R_SwapBuffers                 158
#define V_R_GetBufferDC                 159
#define V_R_ReleaseBufferDC             160
#define V_R_RestoreBuffer               161
#define V_R_SetDisplayLinebytes         162
#define V_R_ReadBuffer                  163
#define V_R_AddToCmdAndDMAList          164
#define V_SUCCESS                       500
#define V_PARAM_ERROR                   501
#define V_ALLOC_FAILED                  502
#define V_CMDBUFFER_INUSE               503
#define V_CMDBUFFER_AVAIL               504
#define V_CMDBUFFER_TOO_SMALL           505
#define V_CMDBUFFER_NO_DMAENTRIES       506
#define V_LOCK_PAGES_FAILED             508
#define V_CANNOT_ISSUE_COMMANDS         509
#define V_CANNOT_SWAP_WINDOWED_SURFACES 510
#define V_CANNOT_LOAD_UCODE             511
#define V_CANNOT_GET_BOARDINFO          512
#define V_OPEN_FAIL_VXD                 513
#define V_NO_ERROR                      514
#define V_IOCTL_VERITE_LOCK_PAGES       515
#define V_IOCTL_VERITE_ALLOC_LOCKED_MEM 516
#define V_PAGE_CHECK                    517
#define V_FAILED                        518
#define V_DD_DIRECTDRAWCREATE           519
#define V_DD_DIRECTDRAW2CREATE          520
#define V_DD_SETLEVEL                   521
#define V_DD_RESTOREDISPLAYMODE         522
#define V_DD_SETDISPLAYMODE             523
#define V_DD_CREATECLIPPER              524
#define V_DD_CREATESURFACE              525
#define V_DD_SETCLIPPER                 526
#define V_DD_ISLOST                     530
#define V_DD_RESTORE                    531
#define V_DD_LOCK                       540
#define V_DD_BLT                        547
#define V_IOCTL_GET_VERITE_INFO         548
#define V_BAD_PIXFMT                    550
#define V_VERITE_COMMAND_ERR            551
#define V_INVALID_BUFFER                552
#define V_DD_UNLOCK                     553
#define V_DD_GETDC                      554
#define V_DD_RELEASEDC                  555
#define V_SUBSURFACE_ERROR              559
#define V_CANNOT_OBTAIN_DC              560
#define V_OUT_OF_VIDEO_MEMORY           561
#define V_FULLSCREEN_MODE_ONLY          625

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
