//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by THRED.rc
//
#define ID_COLOR_DEFAULTS               3
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_DIALOGBAR            103
#define ID_TOOLBAR_COMBOBOX             104
#define IDB_SPLASH                      105
#define IDD_PROPPAGE_MEDIUM             106
#define ID_INDICATOR_BRUSHINFO          110
#define IDR_MAINFRAME                   128
#define IDR_THREDTYPE                   129
#define IDR_BRUSHTOOLS                  130
#define IDD_BRUSHDIALOG                 132
#define IDD_CREATEBOX                   133
#define IDB_HOLLOWBOX                   134
#define IDB_SOLIDBOX                    135
#define IDD_CREATE_SPHEROID             136
#define IDB_SOLIDSPHERE                 137
#define IDB_HOLLOWSPHERE                138
#define IDD_CREATE_CYL                  139
#define IDB_CYLINDERBIT                 140
#define IDD_GRIDSETTINGSDIALOG          141
#define IDB_SOLIDTRIANGLE               141
#define IDD_BSPMANAGERDIALOG            142
#define IDB_HOLLOWTRIANGLE              142
#define IDD_ENTITIES                    143
#define IDD_SELECTCLASSNAME             144
#define IDD_GROUPDIALOG                 145
#define IDD_STAIRCASEDIALOG             146
#define IDR_THRED_PALETTE1              147
#define IDD_GLOBALSETTINGS              148
#define IDD_DIALOG1                     149
#define IDD_NEWFILEDLG                  150
#define IDD_MATERIALVIEW                151
#define IDD_PALMATDIALOG                152
#define IDC_CURSOR1                     153
#define IDD_ASSIGN_TEXTURE              154
#define IDD_CREATETRIANGLE              155
#define IDC_CURSOR2                     156
#define IDD_TSDIALOG                    157
#define IDC_CURSOR3                     158
#define IDB_UARROW                      159
#define IDB_DARROW                      160
#define IDD_LIGHTING_DIALOG             161
#define IDC_CURSOR4                     162
#define IDC_CURSOR5                     163
#define IDB_LIGHTBULB                   164
#define IDD_PICKCOLORDIALOG             168
#define IDD_DIALOG2                     171
#define IDD_BRUSHORDERDIALOG            171
#define IDD_VOLDESCDIALOG               176
#define IDD_LIGHT_DIALOG                180
#define IDD_SCRATCH                     182
#define IDB_LIGHT                       184
#define IDB_DETAIL                      185
#define IDB_STATE                       186
#define IDD_TEMP                        187
#define IDB_LIGHT2                      189
#define IDD_ITR_SHAPE                   193
#define IDD_ITR_LIGHT                   194
#define IDD_ITR_BUILD                   195
#define IDD_DETAILSETTINGS              196
#define IDB_DETAIL2                     199
#define IDD_MATERIALPROPERTIES          200
#define IDD_SUN_EDIT                    202
#define IDD_LIGHTEMITTERPROP            203
#define IDD_LIGHTPROP                   204
#define IDD_LIGHTSTATEPROP              205
#define IDD_LIGHTBLANKPROP              206
#define IDC_RESET_ALL                   1000
#define IDC_EDIT1                       1001
#define IDC_BRUSH_TSIZEREADOUT          1002
#define IDC_LIGHT_LIGHTSCALE            1002
#define IDC_EDIT2                       1003
#define IDC_LD_COLOREDIT                1003
#define IDC_LIGHT_QUANTUM               1003
#define IDC_EDIT3                       1004
#define IDC_LD_DURATIONEDIT             1004
#define IDC_MP_INTENSITYEDIT            1004
#define IDC_EDIT4                       1005
#define IDC_LD_DISTANCE1EDIT            1005
#define IDC_BUILD_GEOMETRYSCALE         1005
#define IDC_EDIT5                       1006
#define IDC_LD_DISTANCE2EDIT            1006
#define IDC_BUILD_SNAPPRECISION         1006
#define IDC_EDIT6                       1007
#define IDC_LD_DISTANCE3EDIT            1007
#define IDC_BUILD_PLANEDISTANCE         1007
#define IDC_EDIT7                       1008
#define IDC_BUILD_TEXTURESCALE          1008
#define IDC_EDIT8                       1009
#define IDC_BUILD_MAXTEXTURE            1009
#define IDC_EDIT9                       1010
#define IDC_BUILD_NORMALPRECISION       1010
#define IDC_RESET_POSITION              1011
#define IDC_RESET_ROTATION              1012
#define IDC_RESET_SCALE                 1013
#define IDC_SOLID                       1014
#define IDC_XShear                      1014
#define IDC_HOLLOW                      1015
#define IDC_YSHEAR                      1015
#define IDC_XSIZE                       1016
#define IDC_ZSHEAR                      1016
#define IDC_RING                        1016
#define IDC_YSIZE                       1017
#define IDC_RESET_SHEAR                 1017
#define IDC_ZSIZE                       1018
#define IDC_THICKNESS                   1019
#define IDC_PICTURE                     1020
#define IDC_VERTSTRIPES                 1021
#define IDC_YSIZE2                      1021
#define IDC_HORSTRIPES                  1022
#define IDC_XSIZE2                      1022
#define IDC_XSIZEBOT                    1023
#define IDC_ZSIZEBOT                    1024
#define IDC_TOPXSIZE                    1025
#define IDC_TOPXOFF                     1026
#define IDC_TOPZOFF                     1027
#define IDC_BOTXSIZE                    1028
#define IDC_BOTZSIZE                    1029
#define IDC_BOTXOFF                     1030
#define IDC_BOTZOFF                     1031
#define IDC_TOPZSIZE                    1032
#define IDC_GRIDSIZE                    1033
#define IDC_RebuildQuick                1035
#define IDC_REBUILDOPTIMAL              1036
#define IDC_ORIGINAL_POLYS              1037
#define IDC_SPLITS                      1038
#define IDC_TOTAL_POLYS                 1039
#define IDC_NODES                       1040
#define IDC_COPLANAR_NODES              1041
#define IDC_Defaults                    1043
#define IDC_PROGRESS1                   1046
#define IDC_PAIRS                       1047
#define IDC_SHOWLIGHTS                  1052
#define IDC_NEWKEYVALUE                 1054
#define IDC_KEY_EDIT                    1055
#define IDC_VALUE_EDIT                  1056
#define IDC_ENTITYLIST                  1057
#define IDC_ASSOCIATE_SELECTEDBRUSH     1058
#define IDC_ASSOCIATEGROUP              1059
#define IDC_NEWENTITY                   1060
#define IDC_NEWLIGHT                    1061
#define IDC_DELETEKEYVALUE              1062
#define IDC_DELETEENTITY                1063
#define IDC_LIST1                       1064
#define IDC_COLOURBUTTON                1065
#define IDC_CHECK1                      1066
#define IDC_LIST2                       1067
#define IDC_XSIZETOP                    1071
#define IDC_ZSIZETOP                    1072
#define IDC_HEIGHT                      1073
#define IDC_WIDTH                       1074
#define IDC_LENGTH                      1075
#define IDC_NUMBEROFSTAIRS              1076
#define IDC_BUILDWATER                  1077
#define IDC_SIZE16                      1078
#define IDC_SIZE32                      1079
#define IDC_SIZE64                      1080
#define IDC_SIZE8                       1081
#define IDC_USEROTSNAP                  1083
#define IDC_SNAP15                      1084
#define IDC_SNAP30                      1085
#define IDC_SNAP45                      1086
#define IDC_SNAP60                      1087
#define IDC_SNAP2_5                     1088
#define IDC_ROTSNAPDEGREES              1089
#define IDC_BROWSEPAL                   1090
#define IDC_SIZE4                       1090
#define IDC_BROWSEWAD                   1091
#define IDC_PALETTEPATH                 1092
#define IDC_WADPATH                     1093
#define IDC_DISASSOCIATE                1094
#define IDC_EDFILENAME                  1095
#define IDC_EDPAL                       1096
#define IDC_PALETTE                     1097
#define IDC_EDARRAY                     1098
#define IDC_ARRAY                       1099
#define OPEN                            1100
#define IDC_EDITINDEX1                  1101
#define IDC_SPINMAT1                    1102
#define IDC_EDITINDEX2                  1103
#define IDC_SPINMAT2                    1104
#define IDC_CANVAS2                     1105
#define IDC_CANVAS1                     1106
#define IDC_ASNEDPAL                    1106
#define IDC_ASNEDARRAY                  1107
#define IDC_ASNPALETTE                  1108
#define IDC_ASNARRAY                    1109
#define IDC_MAT_CANVAS                  1110
#define IDC_MAT_INDEX                   1111
#define IDC_MAT_SPIN                    1112
#define IDC_BRUSH_MAT_CANVAS            1113
#define IDC_BRUSH_MAT_INDEX             1114
#define IDC_BRUSH_MAT_SPIN              1115
#define IDC_GRIDTYPE                    1119
#define IDC_TRIZSIZETOP                 1122
#define IDC_TRIXSIZEBOT                 1123
#define IDC_TRIZSIZEBOT                 1124
#define IDC_TRIYSIZE                    1125
#define IDC_TRITHICKNESS                1126
#define IDC_TRISOLID                    1127
#define IDC_TRIHOLLOW                   1128
#define IDC_FRAME1                      1131
#define IDC_FRAME2                      1132
#define IDC_FRAME3                      1133
#define IDC_VERTICALSLIDER              1134
#define IDC_HORIZONTALSLIDER            1135
#define IDC_FRAME4                      1144
#define IDC_SPINTEXTURE                 1146
#define IDC_ROTDISPLAY                  1147
#define IDC_TEXTURESCALE                1148
#define IDC_UPBUTTON                    1149
#define IDC_DOWNBUTTON                  1150
#define IDC_BBX                         1150
#define IDC_BBY                         1151
#define IDC_LIGHTING_SLIDER             1151
#define IDC_BBZ                         1152
#define IDC_TROT_SHOW                   1152
#define IDC_TSCALE                      1153
#define IDC_TS_DOIT                     1155
#define IDC_ADDRADIO                    1156
#define IDC_SUBTRACTRADIO               1157
#define IDC_RADIO2_5                    1157
#define IDC_RADIO5_0                    1158
#define IDC_RADIO10_0                   1159
#define IDC_VOLRADIO                    1159
#define IDC_RADIO1_0                    1160
#define IDC_COLORSELECT                 1162
#define IDC_BUTTON_TOTOP                1164
#define IDC_BUTTON_TOBOTTOM             1165
#define IDC_BRUSHLIST                   1165
#define IDC_BUTTON_TOFORWARD            1166
#define IDC_BUTTON_BACK                 1166
#define IDC_BUTTON_TOBACK               1167
#define IDC_BUTTON_FORWARD              1167
#define IDC_MININTENSITY                1167
#define IDC_BUTTON_TOP                  1168
#define IDC_TSIZEREADOUT                1168
#define IDC_BUTTON_BOTTOM               1169
#define IDC_VIEWTSIZEREADOUT1           1169
#define IDC_VIEWTSIZEREADOUT2           1170
#define IDC_FLIPHORIZ                   1170
#define IDC_FLIPVERT                    1171
#define IDC_STRETCHCHECK1               1171
#define IDC_STRETCHCHECK2               1172
#define IDC_VOLSELECTION                1175
#define IDC_DEFAULTBUTTON               1176
#define IDC_VOLDESCEDIT                 1177
#define IDC_VOLUMELIST1                 1178
#define IDC_SHOWVOLRADIO                1179
#define IDC_HALFSPHERERADIO             1181
#define IDC_COLORBUTTON                 1182
#define IDC_LD_CREATELIGHT              1184
#define IDC_LD_DELETELIGHT              1185
#define IDC_LD_ADDSTATE                 1186
#define IDC_LD_REMOVESTATE              1187
#define IDC_LD_COLORPICK                1188
#define IDC_LD_LINEARRADIO              1189
#define IDC_LD_QUADRATICRADIO           1190
#define IDC_LD_SPOTRADIO                1192
#define IDC_LD_POINTRADIO               1193
#define IDC_LD_DIRECTIONEDIT            1194
#define IDC_LD_NAMEEDIT                 1196
#define IDC_LD_RANDOMCHECK              1197
#define IDC_LD_LOOPCHECK                1198
#define IDC_LD_AUTOCHECK                1199
#define IDC_LD_STATESPIN                1203
#define IDC_LD_ANGLEEDIT                1204
#define IDC_LD_LIGHTLIST                1205
#define IDC_ID_STATELIST                1206
#define IDC_LD_POSITIONEDIT             1207
#define IDC_LD_APPLY                    1208
#define IDC_LD_TREE                     1210
#define IDC_LD_COPYCURRENT              1214
#define IDC_BUTTON1                     1215
#define IDC_LD_LIGHT                    1215
#define IDC_CLEARAMBIENTBUT             1215
#define IDC_COMBO1                      1216
#define IDC_SETAMBIENTBUT               1216
#define IDC_COMBO2                      1217
#define IDC_BUTTON2                     1218
#define IDC_LS_SUNEDIT                  1218
#define IDC_BUTTON3                     1219
#define IDC_SLIDER1                     1220
#define IDC_TEX_SHIFT                   1220
#define IDC_CHECK2                      1223
#define IDC_LINKEDINTERIOR              1223
#define IDC_CHECK3                      1224
#define IDC_TOP                         1224
#define IDC_CHECK4                      1225
#define IDC_BOTTOM                      1225
#define IDC_CHECK5                      1226
#define IDC_BACK                        1226
#define IDC_CHECK6                      1227
#define IDC_FRONT                       1227
#define IDC_CHECK7                      1228
#define IDC_LEFT                        1228
#define IDC_CHECK8                      1229
#define IDC_RIGHT                       1229
#define IDC_BUILD_LOWDETAIL             1230
#define IDC_LIGHT_GEOMETRYSCALE         1231
#define IDC_LIGHT_USENORMALS            1232
#define IDC_LIGHT_USEMATERIAL           1233
#define IDC_HIGHBUILD                   1234
#define IDC_LIGHTSETS                   1236
#define IDC_MIN_PIXELS                  1237
#define IDC_LD_ID                       1238
#define IDC_ABOUT_VERSION               1239
#define IDC_LD_MANAGEBYMISSIONEDITOR    1240
#define IDC_MP_FLATCOLORRADIO           1241
#define IDC_MP_FLATEMISSIONRADIO        1242
#define IDC_MP_MODIFYCHECK              1243
#define IDC_MP_MATINDEX                 1244
#define IDC_MP_SPINMAT                  1245
#define IDC_MP_CANVAS                   1246
#define IDC_MP_STRETCHCHECK             1247
#define IDC_MP_COLOREDIT                1248
#define IDC_MP_COLORPICK                1249
#define IDC_MP_VIEWSIZE                 1250
#define IDC_TEX_SHIFT_DISPLAY           1252
#define IDC_EDIT                        1255
#define IDC_AMBIENTLIGHT                1256
#define IDC_AMBIENTCHECK                1257
#define IDC_AMBIENT_OUTSIDE             1262
#define IDC_PALETTEVOL                  2000
#define IDC_EDPALVOL                    2001
#define IDC_TEXTUREVOL                  2002
#define IDD_RECT0                       2002
#define IDC_EDMATVOL                    2003
#define ID_BRUSH_PRIMITIVES_CUBE        32771
#define ID_BRUSH_PRIMITIVES_PYRAMID     32772
#define ID_BRUSH_PRIMITIVES_SPHEROID    32772
#define ID_BRUSH_PRIMITIVES_CONE        32773
#define ID_BRUSH_PRIMITIVES_CYLINDER    32773
#define ID_BRUSH_ADDTOWORLD             32774
#define ID_BRUSH_SUBTRACTFROMWORLD      32775
#define ID_TOOLS_CAMERA                 32776
#define ID_AXIS_X                       32781
#define ID_AXIS_Y                       32782
#define ID_AXIS_Z                       32783
#define ID_TOOLS_BRUSH_MOVEROTATEBRUSH  32784
#define ID_TOOLS_BRUSH_SCALEBRUSH       32785
#define ID_TOOLS_BRUSH_RESETBRUSH       32786
#define ID_TOOLS_BRUSH_ATTRIBUTES       32791
#define ID_TOOLS_BRUSH_SHOWBRUSH        32792
#define ID_FILE_EXPORT                  32799
#define ID_TOOLS_USEGRID                32801
#define ID_TOOLS_GRIDSETTINGS           32802
#define ID_VIEW_3DWIREFRAME             32806
#define ID_VIEW_SOLIDRENDER             32807
#define ID_VIEW_TOPVIEW                 32808
#define ID_VIEW_SIDEVIEW                32809
#define ID_VIEW_FRONTVIEW               32810
#define ID_VIEW_TEXTUREVIEW             32811
#define ID_VIEW_4VIEWS                  32812
#define ID_TOOLS_BSPMANAGER             32813
#define ID_TOOLS_BRUSH_SHEARBRUSH       32814
#define ID_ENTITIES_PLACE               32817
#define ID_ENTITIES_EDITOR              32819
#define ID_TOOLS_ENTITY                 32823
#define ID_ENTITIES_SHOW                32824
#define ID_TOOLS_TEXTURES               32826
#define ID_BRUSH_GROUPS_ADDTOGROUP      32832
#define ID_BRUSH_GROUPS_MAKENEWGROUP    32833
#define ID_BRUSH_GROUPEDITOR            32834
#define ID_BRUSH_GROUPS_SELECT          32835
#define ID_VIEW_SHOW_ALLBRUSHES         32836
#define ID_VIEW_SHOW_VISIBLEBRUSHES     32837
#define ID_VIEW_SHOW_CURRENTGROUP       32838
#define ID_BOGUS_1                      32839
#define ID_BOGUS_2                      32840
#define ID_BRUSH_ADJUSTMENTMODE         32849
#define ID_BRUSH_SELECTED_DELETE        32850
#define ID_BRUSH_SELECTED_NEXTINORDER   32851
#define ID_BRUSH_SELECTED_PREVIOUSINORDER 32852
#define ID_BRUSH_SELECTED_COPYTOCURRENT 32853
#define ID_BRUSH_PRIMITIVES_STAIRCASE   32856
#define ID_TOOLS_BRUSH_ROTATE90         32857
#define ID_VIEW_TEXTUREBROWSER          32859
#define ID_FILE_MAPSETTINGS             32860
#define ID_QBSPNOWATER                  32861
#define ID_ENTITIES_COPYCURRENT         32862
#define ID_TOOLS_BRUSH_MOVESELECTEDBRUSHES 32867
#define ID_TOOLS_GROUPMOVEMENTMODE      32870
#define ID_BRUSH_REMOVESELECTEDFROMGROUP 32871
#define ID_TEXTURE_EDIT_FACE            32875
#define ID_BRUSH_PRIMITIVES_TRIANGLE    32878
#define ID_TOOLS_SETTEXTURESCALE        32881
#define ID_EDIT_MODE_BUTTON             32882
#define ID_TOOLS_SET                    32883
#define ID_TOOLS_SETLIGHTING            32884
#define ID_FILE_EXPORTOPTIMAL           32885
#define ID_TOOLS_LOADNEWPALETTE         32886
#define ID_TOOLS_TEXTURESCALE           32888
#define ID_BRUSH_COPYTONEWGROUP         32889
#define ID_VIEW_OLDVIEW                 32890
#define ID_VIEW_CENTERCAMERAATORIGIN    32890
#define ID_TOOLS_CENTERCAM              32891
#define ID_VIEW_ZOOMIN                  32892
#define ID_VIEW_ZOOMOUT                 32893
#define ID_BUTTON32894                  32894
#define ID_TOOLS_SELECTNMOVE            32895
#define ID_ACCEL32897                   32897
#define IDC_LD_NONERADIO                32897
#define ID_TOOLS_SETBACKGROUNDCOLOR     32898
#define ID_FILE_IMPORTBRUSHGROUP        32900
#define ID_FILE_EXPORTBRUSHGROUP        32901
#define ID_EDIT_SELECTALL               32902
#define ID_BRUSH_ADJUSTBRUSHORDER       32904
#define ID_BRUSH_REORDER                32905
#define ID_COMPUTELIGHTING              32907
#define ID_TOOLS_CALCULATELIGHTING      32908
#define ID_FILE_GENERATELIGHTTABLEREPORT 32909
#define ID_TOOLS_ASSIGNVOLUMES          32910
#define ID_VIEW_SHOW_VOLUMES            32911
#define ID_BUTTON32912                  32912
#define ID_BUTTONSHOWFILLEDVOLUMES      32913
#define ID_VIEW_SHOW_FILLEDVOLUMES      32916
#define ID_ENTITIES_DELETESELECTED      32917
#define ID_DELETESELECTIONS             -32618
#define ID_VIEW_TEST                    32919
#define ID_LIGHTS_COPYCURRENT           32921
#define ID_LIGHTS_EDITOR                32922
#define ID_LIGHTS_SHOW                  32923
#define ID_LIGHTS_PLACE                 32924
#define ID_LIGHTS_DELETESELECTED        32930
#define ID_VIEW_OBJECTVIEWER            32935
#define ID_VIEW_GROUPVIEWER             32936
#define ID_VIEW_TEXTUREVIEWER           32937
#define ID_FILE_EXPORTAS                32938
#define ID_LIGHT_LOCKMOVE               32939
#define ID_LOCKTEXTUREPOSITIONS         32941
#define ID_VIEW_MATERIALPROPERTIES      32942
#define ID_ENTITIES_SHOW3D              32943
#define ID_LIGHTS_SHOW3D                32944
#define ID_ENTITIES_CONVERT             32945
#define ID_LIGHTS_SHOWFALLOFFS          32946
#define ID_GRIDINFORMATION              61216
#define ID_INDICATOR_POS                61217
#define ID_VIEWBUTTON                   62000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32947
#define _APS_NEXT_CONTROL_VALUE         1263
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
