#define ID_FILE_NEW				101
#define ID_FILE_OPEN			102
#define ID_FILE_SAVE			103
#define ID_FILE_SAVE_AS			104
#define ID_FILE_PRINTER_SETUP	105
#define ID_FILE_PAGE_SETUP		106
#define ID_FILE_PRINT			107
#define ID_FILE_EXIT			108

#define ID_EDIT_UNDO			201
#define ID_EDIT_REDO			202
#define ID_EDIT_CUT				203
#define ID_EDIT_COPY			204
#define ID_EDIT_PASTE			205

#define ID_POPUP_WINSHOW             401
#define ID_POPUP_WINHIDE             402
#define ID_POPUP_STATSHOW            403
#define ID_POPUP_STATHIDE            404
#define ID_POPUP_TOOLSHOW            406
#define ID_POPUP_TOOLHIDE            405

#define IDB_TOOLBAR				500
#define IDM_NEW					200
#define IDM_OPEN				   300
#define IDM_SAVE				   400
#define IDM_CUT					500
#define IDM_COPY				   600
#define IDM_PASTE				   700
#define IDM_PRINT				   800
#define IDM_HELP				   900
#define IDM_ONHELP				1000

#define IDB_BITMAP1                     516
